package main

import (
	"github.com/kenshin579/analyzing-golang-echo-realworld-example-app/db"
	"github.com/kenshin579/analyzing-golang-echo-realworld-example-app/handler"
	"github.com/kenshin579/analyzing-golang-echo-realworld-example-app/router"
	"github.com/kenshin579/analyzing-golang-echo-realworld-example-app/store"

	_ "github.com/kenshin579/analyzing-golang-echo-realworld-example-app/docs" // docs is generated by Swag CLI, you have to import it.
	echoSwagger "github.com/swaggo/echo-swagger"                               // echo-swagger middleware
)

// @title Swagger Example API
// @version 1.0
// @description Conduit API
// @title Conduit API

// @host 127.0.0.1:8585
// @BasePath /api

// @schemes http https
// @produce	application/json
// @consumes application/json

// @securityDefinitions.apikey ApiKeyAuth
// @in header
// @name Authorization

func main() {
	router := router.New()

	router.GET("/swagger/*", echoSwagger.WrapHandler)

	v1 := router.Group("/api")

	database := db.New()
	db.AutoMigrate(database)

	//repository 역할을 함
	userStore := store.NewUserStore(database)
	articleStore := store.NewArticleStore(database)

	handler := handler.NewHandler(userStore, articleStore)
	handler.Register(v1)
	router.Logger.Fatal(router.Start("127.0.0.1:8080"))
}
